FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/network-manager ./services/network-manager

FROM alpine:latest
RUN apk add --no-cache nftables iproute2
WORKDIR /app
COPY --from=builder /app/network-manager /app/network-manager
EXPOSE 8081
CMD ["./network-manager"]
